dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  - smartcontractkit/chainlink@1.2.1

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@chainlink=smartcontractkit/chainlink@1.2.1"

dotenv: .env
